Expand auto-tag

diff --git a/.github/workflows/auto-tag.yml b/.github/workflows/auto-tag.yml
--- a/.github/workflows/auto-tag.yml
+++ b/.github/workflows/auto-tag.yml
@@ -1,7 +1,6 @@
-name: Create tag based on crate version
+name: Automatically create draft release when crate version increased
 
 on:
-  workflow_dispatch:
   push:
     branches: [ "main" ]
 
@@ -26,10 +25,38 @@ jobs:
       run: 
         cargo metadata -q --no-deps --format-version 1 | jq '.packages[] | select(.name == "discord-rpc-helper") | .version' | tr -d \" | tee version.txt ;
         echo "cargo_version=$(cat version.txt)" >> $GITHUB_OUTPUT ;
-      
+        echo "Crate is currently at version v$(cat version.txt)" >> $GITHUB_STEP_SUMMARY;
+
+    - name: 'Get Previous tag'
+      id: previoustag
+      uses: "WyriHaximus/github-action-get-previous-tag@v1"
+    
+    - name: Check if version has actually increased
+      run: |
+        crate_version = "v" + ${{ steps.crateVersion.outputs.cargo_version }}
+        if [ ${{ steps.previoustag.outputs.tag == $crate_version }}];
+        then
+          echo "::error ::Crate version is still $crate_version";
+          exit 1;
+        else
+          echo "::notice title=Crate version increased::The version of the crate was increased from ${{ steps.previoustag.outputs.tag }} to $crate_version";
+        fi
+
     - name: Bump version and push tag
       id: tag_version
       uses: mathieudutour/github-tag-action@v6.0
       with:
         github_token: ${{ github.token }}
         custom_tag: ${{ steps.crateVersion.outputs.cargo_version }}
+      
+
+  auto_draft_release:
+    name: Create draft release based on tag
+    
+    runs-on: ubuntu-latest
+    needs: auto_tag
+
+    steps:
+      - name: stub
+        run: echo "This is just a stub for now"
+    
